package com.nourmina.jobportal.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Document  // This tells Spring to save this class as a MongoDB document
public class Application {
    @Id
    private String id;  // Unique ID for each application, generated by the database

    public static final String STATUS_APPLIED = "APPLIED";
    public static final String STATUS_SHORTLISTED = "SHORTLISTED";
    public static final String STATUS_REJECTED = "REJECTED";
    public static final String STATUS_PENDING = "PENDING"; // Added to match usage in service

    private String candidateId;    // ID of the candidate applying for the job
    private String jobPostingId;   // ID of the job the candidate applied to
    private String status;         // The current status of the application
    private LocalDateTime appliedDate;

    // Constructor
    public Application() {
        this(null, null, null);
    }

    public Application(String candidateId, String jobPostingId, String status) {
        this.candidateId = candidateId;
        this.jobPostingId = jobPostingId;
        this.status = status;
        this.appliedDate = LocalDateTime.now(); // Set the application date and time to now
    }

    // Getters and setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCandidateId() {
        return candidateId;
    }

    public void setCandidateId(String candidateId) {
        this.candidateId = candidateId;
    }

    public String getJobPostingId() {
        return jobPostingId;
    }

    public void setJobPostingId(String jobPostingId) {
        this.jobPostingId = jobPostingId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        if (STATUS_APPLIED.equals(status) ||
                STATUS_SHORTLISTED.equals(status) ||
                STATUS_REJECTED.equals(status) ||
                STATUS_PENDING.equals(status)) {
            this.status = status;
        }
    }

    public LocalDateTime getAppliedDate() {
        return appliedDate;
    }

    public void setAppliedDate(LocalDateTime appliedDate) {
        this.appliedDate = appliedDate;
    }
}
